### ISSUE TITLE
webjar-manifest proposal

### ISSUE THREAD

**Issue by gejgalis** [webjars/webjars-maven-plugin#14]
Hello James!

We (me and a lot of teams where I'm working today) are using webjars for a while and we see how that improved our daily work with JS packages in Java world. I promote this kind of JS reuse everywhere I can.

I'm automation enthusiast and I wanted to figure out how more effectively use webjars in following situations:
- **Unit Tests** We use [jasmine-maven-plugin](http://searls.github.io/jasmine-maven-plugin/) for unit tests. I made little contribution to this project to allow access JS files belonging to dependent webjars in easy way (ie.: `http://localhost:8234/webjars/jquery.js`). We are not satisfied in 100% because we need to enumerate in plugin configuration all dependent JS files that were already declared in `<dependencies>` section. There is a way to have custom Jasmine runner defined as HTML/JavaScript page but it is very hard to get all information about JS dependency tree there and **it needs to hardcode load configuration there**.
- **index-dev.html** We use different page loading configurations for **PROD** and **DEV**. In PROD we use several strategies of merged and minified JS dependencies and it must be hardcoded manually. In DEV enviroment we load all needed dependent JS (and it doesn't matter if we use requireJS or not) file by file. Those files shouldn't be minified for easier debugging. If we want to use just static HTML page without any Java framework then again **it needs to hardcode load configuration there**. Moreover we want to automatically include **CSS** files belonging to webjars dependencies and we have to do it manually.

Our proposal is to introduce **webjar-manifest** which could extend information about webjar content in more generic way than existing `webjars-requirejs.js` configuration. We could use **webjar-manifest** to generate `webjars-requirejs.js` or any other module loader configuration.

**webjar-manifest** should deliver following information:
- `name` - webjar name (usually it will be `${project.build.artifactId}` but our intention is to keep here AMD module name in case when main JS file of this webjar contains named AMD module defined by `define('my-name', ...`
- `js` - one path to main JS file which should be loaded
- `css` - one or more paths to CSS files which should be loaded
- `exports` - name of global variable that is produced by library in case of not AMD module. It can be used to build `shim` configuration for RequireJS.
- `defaultSymbol` - name of recommended symbol name which should be used as dependency handler ie: `define(["lodash"], function (_) {// we use _ as lodash default symbol here});`
- `dependencies` - collection of dependent webjars using following structure:
  - `name` - name of dependant webjar

Above description doesn't resolve **DEV** and **PROD** differences in configuration. We may use something similar to `<profiles>` known from Maven. Profile may be defined as `"dev"`, but it also may be used for other contexts like `"test"` or `"compat"`, `"underscore"` in case of LoDash library when there is more than one main JS files.

**webjar-manifest** is a file placed in jar at path `/META-INF/resources/webjars/foo/1.0.0/foo.manifest.json`.

Let see some example manifests:

``` json
// jquery.manifest.json
{
    "manifest": {
        "name": "jquery",
        "js": "{basePath}/jquery.min.js",

        "exports": "$",

        "profiles": {
            "dev": {
                "js": "{basePath}/jquery.min.js"
            }
        }
    }
}

// jquery-ui.manifest.json
{
    "manifest": {
        "name": "jquery-ui",
        "js": "{basePath}/ui/minified/jquery-ui.min.js",
        "css": "{basePath}/themes/base/minified/jquery-ui.min.css",

        "exports": "$",

        "dependencies": [
            {"name": "jquery"}
        ],

        "profiles": {
            "dev": {
                "js": "{basePath}/ui/minified/jquery-ui.min.js",
                "css": "{basePath}/themes/base/minified/jquery-ui.min.css",
            }
        }
    }
}

// lodash.manifest.json
{
    "manifest": {
        "name": "lodash",
        "js": "{basePath}/lodash.min.js",

        "profiles": {
            "lodash.compat": {
                "js": "{basePath}/lodash.compat.min.js"
            },
            "lodash.underscore": {
                "js": "{basePath}/lodash.underscore.min.js"
            },

            "dev": {
                "js": "{basePath}/lodash.js"
            },
            "dev,lodash.compat": {
                "js": "{basePath}/lodash.compat.js"
            },
            "dev,lodash.underscore": {
                "js": "{basePath}/lodash.underscore.js"
            }
        }
    }
}

// some-css-theme.manifest.json
{
    "manifest": {
        "name": "some-css-theme",
        "css": "{basePath}/some-css-theme.min.css",

        "profiles": {
            "dev": {
                "css": "some-css-theme.css"
            }
        }
    }
}
```

So we have defined **webjar-manifests** and we want to use it somehow. We propose to add to [webjars-maven-plugin](https://github.com/webjars/webjars-maven-plugin) a new goal named `export-manifests`. The configuration of this goal should take following parameters:
- `outputPath` - path to result file (let say by default it will be `target/webjars/manifests-list.json`
- `profiles` - list of profiles separated by comma. When omitted no profile will be processed.
- `globalVariable` [optional] - name of global variable where JSON will be assigned. When omitted no global assignment will be performed.
- `baseUrl` [optional] - a path before `webjars/...`. Default: `""` 

Let define `foo` webjar which has following **webjar-manifest**:

``` json
// foo.manifest.json
{
    "manifest": {
        "name": "foo",
        "js": "{basePath}/foo.min.js",

        "dependencies": [
            {"name": "jquery-ui"},
            {"name": "lodash"},
        ],

        "profiles": {
            "dev": {
                "js": "{basePath}/foo.js"
            },

            "test" : {
                // we want to extend "dependencies" instead of replacing the default ones 
                "extend": {
                    "dependencies": [
                        {"name": "jasmine-async"}
                    ]
                }
            }
        }
    }
}
```

Let execute `webjars-maven-plugin:export-manifests` without any profile and check what is in outputPath:

``` json
// no profile selected
{
    "manifests": [
        {
            "name": "lodash",
            "js": "webjars/lodash/2.4.1/lodash.min.js"
        },
        {
            "name": "jquery",
            "js": "webjars/jquery/1.10.1/jquery.min.js",
            "exports": "$"
        },
        {
            "name": "jquery-ui",
            "js": "webjars/jquery-ui/1.10.2/ui/minified/jquery-ui.min.js",
            "css": "webjars/jquery-ui/1.10.2/themes/base/minified/jquery-ui.min.css",
            "exports": "$",
            "dependencies": [
                {"name": "jquery"}
            ]
        },
        {
            "name": "foo",
            "js": "webjars/foo/1.0.0/foo.min.js",

            "dependencies": [
                {"name": "jquery-ui"},
                {"name": "lodash"}
            ]
        }
    ]
}
```

Notice that:
1. Exported manifests list is ordered by topological sort algorithm of webjars dependency tree.
2. `{basePath}` is replaced to path resolved by `WebJarAssetLocator`.

Let execute `webjars-maven-plugin:export-manifests` with profiles `dev,lodash.compat` and global variable `projectManifests` and check what is in outputPath:

``` javascript
// selected profiles: ["dev","lodash.compat"]
// selected global variable: "projectManifests"

var projectManifests = {
    "manifests": [
        {
            "name": "lodash",
            "js": "webjars/lodash/2.4.1/lodash.compat.js" 
        },
        {
            "name": "jquery",
            "js": "webjars/jquery/1.10.1/jquery.js",
            "exports": "$"
        },
        {
            "name": "jquery-ui",
            "js": "webjars/jquery-ui/1.10.2/ui/jquery-ui.js",
            "css": "webjars/jquery-ui/1.10.2/themes/base/jquery-ui.css",
            "exports": "$",
            "dependencies": [
                {"name": "jquery"}
            ]
        },
        {
            "name": "foo",
            "js": "webjars/foo/1.0.0/foo.js",

            "dependencies": [
                {"name": "jquery-ui"},
                {"name": "lodash"}
            ]
        }
    ]
}
```
# Summary
1. Exported manifests list as a JSON file may be used by Java or JavaScript in order to build custom tools related to build/deploy in easier way.
2. Manifest may contain more properties needed by custom requirements (useful when developing private webjars and private solutions).
3. [webjars-maven-plugin](https://github.com/webjars/webjars-maven-plugin) may validate paths for JS and CSS.
4. **webjar-manifest** idea requires to upgrade existing webjars by adding `webjar-manifest.json` file to each package. To simplify this step we could implement also `auto-discover` algorithm to guess main JS/CSS files using existing RequireJS configuration where available or by filename convention of simple webjars (`webjars/foo/1.0.0/foo.js` as DEV and `webjars/foo/1.0.0/foo.min.js` as PROD).
5. We may contribute to [webjars-maven-plugin](https://github.com/webjars/webjars-maven-plugin) and some popular webjars (to put manifests there).

James, what do you think about proposed enhancement?

Regards,
Piotr

**Comment by jamesward** [comment]
Hi @gejgalis - Thanks for the detailed proposal!

The [webjars-locator](https://github.com/webjars/webjars-locator) project has been the primary place to address this kind of stuff.  For instance...  Play extracts all of the WebJars in it's build process so that the resources are available for testing and the asset pipeline.  We also already have a bunch of this metadata in the pom which goes into the WebJar via the RequireJS support, like:
https://github.com/webjars/bootstrap/blob/master/pom.xml#L55
https://github.com/webjars/jquery/blob/master/pom.xml#L47

`webjars-locator` parses the `pom.xml` for each WebJar to generate the necessary RequireJS config.  We could do the same thing for other metadata so it is all in one file.  But I'd like to see `webjars-locator` be the place that manages that.  We've intentionally kept it lightweight with minimal dependencies.  Also I'd like to make sure we avoid duplication of metadata since that gets tough to maintain.

**Comment by gejgalis** [comment]
I'm sorry for late response. I haven't noticed you added `<requirejs>` tag into `pom.xml`. It looks promising and it may be the best place to address my manifest proposal. I'll move this conversation to `webjars-locator` project after applying some changes related to use `<requirejs>` property. However I'm opting to add some features to `webjars-maven-plugin` like exporting all manifests into one file (this feature will be using `webjars-locator` under the hood).

**Comment by jamesward** [comment]
Sounds good.
